
[main]
tty="/dev/ttyUSB0"
modbus_debug=false
item_mstime=1000
list_mstime=60000
listen_socket="/tmp/tty_reader.socket"

# pzem on charger 1
[id3]
read_address=0
read_count=0
read_input_address=0
read_input_count=8

# pzem on charger 2
[id6]
read_address=0
read_count=0
read_input_address=0
read_input_count=8

# renogy
[id9]
read_address=256
read_count=10
read_input_address=0
read_input_count=0

# pzem on 12v closet
[id10]
read_address=0
read_count=0
read_input_address=0
read_input_count=8

# temp sensor
[id11]
read_address=0
read_count=0
read_input_address=1
read_input_count=2

# ac pzem on charger 1
[id12]
read_address=0
read_count=0
read_input_address=0
read_input_count=10

#[id4]
#read_address=0
#read_count=4
#read_input_address=0
#read_input_count=8

#[id5]
#read_address=0
#read_count=4
#read_input_address=0
#read_input_count=8

#[id7]
#read_address=0
#read_count=4
#read_input_address=0
#read_input_count=8

#[id8]
#read_address=0
#read_count=4
#read_input_address=0
#read_input_count=8
